### PR TITLE
placeholder commit

### PR DESCRIPTION
**Pull request by andrewbheyer**
When accepted will squash and merge.

### CODE REVIEW

**Review by tribeiro — COMMENTED** [review]
I think `Observation` (https://github.com/lsst-ts/ts_observatory_model/blob/ef247e6209769a3754081c4fed5b899329047466/python/lsst/ts/observatory/model/observation.py#L62) also needs to be updated...

**Comment by andrewbheyer** [comment]
Updated to do what? Did you get an error?

**Comment by andrewbheyer** [comment]
Oh nvm, I see what you're saying. Yes, if it is referring to a SAL topic then yes the attributes need to be updated. 

I updated the referenced attributes to `topic` on the method `from_topic()`

**Comment by tribeiro** [comment]
Need to fix these two lines on the `test_target` script:

https://github.com/lsst-ts/ts_observatory_model/blob/f1b94eb208059857718d1e811ebf525b4f25a64f/tests/test_target.py#L90

https://github.com/lsst-ts/ts_observatory_model/blob/f1b94eb208059857718d1e811ebf525b4f25a64f/tests/test_target.py#L95

**Comment by tribeiro** [comment]
Actually the entire test needs fixing. It should be:

```python
    def test_creation_from_topic(self):
	topic = collections.namedtuple('topic', ['targetId', 'fieldId',
                                                 'filter', 'ra', 'decl',
                                                 'skyAngle',
                                                 'numExposures',
                                                 'exposureTimes'])
	topic.targetId = 1
        topic.fieldId = -1
        topic.filter = 'z'
        topic.ra = 274.279376
        topic.decl = -14.441534
        topic.skyAngle = 45.0
        topic.numExposures = 3
        topic.exposureTimes = [5.0, 10.0, 5.0]
        target = Target.from_topic(topic)
        self.assertEqual(target.targetid, topic.targetId)
	self.assertEqual(target.fieldid, topic.fieldId)
        self.assertEqual(target.filter, topic.filter)
        self.assertEqual(target.ra, topic.ra)
        self.assertAlmostEqual(target.dec, topic.decl, delta=1e-7)
        self.assertEqual(target.num_exp, topic.numExposures)
        self.assertListEqual(target.exp_times, topic.exposureTimes)
```

**Review by tribeiro — APPROVED** [review]

**Pull request merged**
